import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { getAnimals, AnimalDesc } from "../lib/animals";

export async function getStaticProps() {
  const animals = getAnimals();
  return {
    props: {
      animals,
    },
  };
}

export default function Home({ animals }: { animals: AnimalDesc[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Choose a pet</h1>

        <div className={styles.grid}>
          {animals.map(({ id, name, description }) => (
            <Link href={`/${id}`} key={id}>
              <a>
                <div className={styles.card}>
                  <img
                    src={"/img/" + id + ".png"}
                    alt={name}
                    width={250}
                    height={250}
                  />
                  <h2>{name}</h2>
                  <p>{description}</p>
                </div>
              </a>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.flaticon.com/packs/animal-silhouettes"
          title="Flat icons"
        >
          Animal Icons created by Freepik - Flaticon
        </a>
      </footer>
    </div>
  );
}
